-- ============================================================
-- URBAN DZ — Supabase schema
-- Paste this whole file into: Supabase Dashboard > SQL Editor > New query > Run
-- Safe to run again: policies and functions are dropped and recreated,
-- your data (products, orders, zone prices) is kept.
--
-- This file IS the real security of the site. The website is static, so the
-- browser talks to Postgres directly with a public key. The rules below —
-- not the JavaScript — decide what anyone may read or write.
-- ============================================================

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name_fr text not null,
  name_ar text not null,
  name_en text not null default '',
  image text not null default '',
  sort int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name_fr text not null,
  name_ar text not null,
  name_en text not null default '',
  description_fr text default '',
  description_ar text default '',
  description_en text default '',
  price numeric not null check (price >= 0),
  compare_at_price numeric check (compare_at_price >= 0),
  photos text[] not null default '{}',
  sizes text[] not null default '{"S","M","L","XL","XXL"}',
  colors text[] not null default '{}',
  category_id bigint references categories(id) on delete set null,
  stock int not null default 0 check (stock >= 0),
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- cash on delivery only — no online payment anywhere in this project
create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null default '',
  zone text not null,
  delivery_fee numeric not null default 0,
  items jsonb not null,
  subtotal numeric not null,
  discount numeric not null default 0,
  promo_code text not null default '',
  total numeric not null,
  status text not null default 'new'
        check (status in ('new','confirmed','shipped','delivered','cancelled')),
  delivery_type text not null default 'home' check (delivery_type in ('home','desk')),
  carrier text not null default '',
  tracking_number text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists orders_created_at_idx on orders (created_at desc);
create index if not exists orders_phone_idx on orders (phone, created_at desc);

create table if not exists settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into settings (key, value) values
  ('store', '{"name":"URBAN DZ","phone":"","email":""}'),
  ('zones', '[]'),
  ('promo', '{"active":false,"percent":0}'),
  ('free_delivery_from', 'null'),
  ('hero', '""'),
  ('whatsapp', '""'),
  ('announce', '{"active":false,"text_fr":"","text_ar":""}'),
  ('socials', '{"instagram":"","facebook":"","tiktok":""}'),
  ('exchange_days', '7'),
  ('ads', '{"metaPixelId":"","tiktokPixelId":""}')
on conflict (key) do nothing;

create table if not exists promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  percent int not null check (percent between 1 and 90),
  min_order numeric not null default 0 check (min_order >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table categories alter column id set generated by default;
alter table products   alter column id set generated by default;
alter table orders     alter column id set generated by default;

-- ---------- THE 58 WILAYAS ----------
-- Starting prices only — set your real tariffs in the dashboard (Zones tab).
-- Re-running MERGES: a wilaya you already priced keeps your numbers.
do $$
declare
  canonical jsonb := $j$[{"code":1,"name":"Adrar","desk":900,"home":1400},{"code":2,"name":"Chlef","desk":400,"home":600},{"code":3,"name":"Laghouat","desk":500,"home":800},{"code":4,"name":"Oum El Bouaghi","desk":500,"home":750},{"code":5,"name":"Batna","desk":500,"home":750},{"code":6,"name":"Bejaia","desk":450,"home":650},{"code":7,"name":"Biskra","desk":550,"home":850},{"code":8,"name":"Bechar","desk":800,"home":1200},{"code":9,"name":"Blida","desk":400,"home":500},{"code":10,"name":"Bouira","desk":450,"home":650},{"code":11,"name":"Tamanrasset","desk":900,"home":1600},{"code":12,"name":"Tebessa","desk":500,"home":800},{"code":13,"name":"Tlemcen","desk":450,"home":700},{"code":14,"name":"Tiaret","desk":500,"home":750},{"code":15,"name":"Tizi Ouzou","desk":450,"home":650},{"code":16,"name":"Alger","desk":400,"home":500},{"code":17,"name":"Djelfa","desk":500,"home":800},{"code":18,"name":"Jijel","desk":450,"home":700},{"code":19,"name":"Setif","desk":450,"home":700},{"code":20,"name":"Saida","desk":500,"home":750},{"code":21,"name":"Skikda","desk":450,"home":700},{"code":22,"name":"Sidi Bel Abbes","desk":450,"home":700},{"code":23,"name":"Annaba","desk":450,"home":700},{"code":24,"name":"Guelma","desk":450,"home":700},{"code":25,"name":"Constantine","desk":450,"home":650},{"code":26,"name":"Medea","desk":450,"home":650},{"code":27,"name":"Mostaganem","desk":450,"home":700},{"code":28,"name":"M'Sila","desk":500,"home":750},{"code":29,"name":"Mascara","desk":450,"home":700},{"code":30,"name":"Ouargla","desk":700,"home":1100},{"code":31,"name":"Oran","desk":450,"home":650},{"code":32,"name":"El Bayadh","desk":700,"home":1100},{"code":33,"name":"Illizi","desk":900,"home":1600},{"code":34,"name":"Bordj Bou Arreridj","desk":450,"home":700},{"code":35,"name":"Boumerdes","desk":400,"home":550},{"code":36,"name":"El Tarf","desk":500,"home":750},{"code":37,"name":"Tindouf","desk":900,"home":1600},{"code":38,"name":"Tissemsilt","desk":500,"home":800},{"code":39,"name":"El Oued","desk":600,"home":950},{"code":40,"name":"Khenchela","desk":500,"home":750},{"code":41,"name":"Souk Ahras","desk":500,"home":750},{"code":42,"name":"Tipaza","desk":400,"home":550},{"code":43,"name":"Mila","desk":450,"home":700},{"code":44,"name":"Ain Defla","desk":450,"home":650},{"code":45,"name":"Naama","desk":700,"home":1100},{"code":46,"name":"Ain Temouchent","desk":450,"home":700},{"code":47,"name":"Ghardaia","desk":600,"home":950},{"code":48,"name":"Relizane","desk":450,"home":650},{"code":49,"name":"Timimoun","desk":900,"home":1400},{"code":50,"name":"Bordj Badji Mokhtar","desk":900,"home":1600},{"code":51,"name":"Ouled Djellal","desk":550,"home":850},{"code":52,"name":"Beni Abbes","desk":800,"home":1200},{"code":53,"name":"In Salah","desk":900,"home":1600},{"code":54,"name":"In Guezzam","desk":900,"home":1600},{"code":55,"name":"Touggourt","desk":600,"home":950},{"code":56,"name":"Djanet","desk":900,"home":1600},{"code":57,"name":"El M'Ghair","desk":600,"home":950},{"code":58,"name":"El Meniaa","desk":700,"home":1100}]$j$;
  current_zones jsonb;
  merged jsonb := '[]'::jsonb;
  w jsonb; old jsonb;
begin
  select value into current_zones from settings where key = 'zones';
  current_zones := coalesce(current_zones, '[]'::jsonb);
  for w in select * from jsonb_array_elements(canonical) loop
    select z into old from jsonb_array_elements(current_zones) z
    where lower(btrim(z->>'name')) = lower(btrim(w->>'name')) limit 1;
    merged := merged || jsonb_build_object(
      'code', w->'code', 'name', w->>'name',
      'home', coalesce(old->'home', old->'fee', w->'home'),
      'desk', coalesce(old->'desk', w->'desk'));
  end loop;
  update settings set value = merged, updated_at = now() where key = 'zones';
end $$;

-- ============================================================
-- OWNERSHIP — the FIRST account created becomes the owner.
-- Create it in Authentication > Users > Add user (Auto Confirm), then turn
-- OFF "Allow new users to sign up". Check with:  select * from owners;
-- ============================================================
create table if not exists owners (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table owners enable row level security;

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public, pg_temp
as $$ select exists (select 1 from owners where user_id = auth.uid()) $$;

create or replace function public.claim_ownership()
returns trigger language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  insert into owners (user_id) select new.id where not exists (select 1 from owners);
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.claim_ownership();

-- ---------- Algerian mobile validation → canonical 0XXXXXXXXX ----------
create or replace function public.dz_phone(p_phone text)
returns text language sql immutable
as $$
  select case when d ~ '^[567][0-9]{8}$' then '0' || d else null end
  from (
    select regexp_replace(
             regexp_replace(regexp_replace(regexp_replace(coalesce(p_phone,''), '\D','','g'), '^00',''), '^213',''),
           '^0','') as d) t
$$;

-- ============================================================
-- PLACING AN ORDER
-- Visitors cannot insert into `orders` directly — that would let them choose
-- the prices. They call place_order(), which rebuilds the basket from the
-- real products table, applies promos and free delivery, and reserves stock.
-- ============================================================
drop function if exists public.place_order(text,text,text,text,jsonb);
drop function if exists public.place_order(text,text,text,text,jsonb,text);
drop function if exists public.place_order(text,text,text,text,jsonb,text,text);

create or replace function public.place_order(
  p_name text, p_phone text, p_address text, p_zone text, p_items jsonb,
  p_promo_code text default '', p_delivery_type text default 'home'
)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  line jsonb; prod products%rowtype; v_pid bigint; v_qty int; v_size text; v_color text;
  clean jsonb := '[]'::jsonb;
  v_sub numeric := 0; v_fee numeric; v_id bigint;
  v_promo_pct numeric := 0; v_unit numeric;
  v_code promo_codes%rowtype; v_discount numeric := 0; v_applied_code text := '';
  v_free_from numeric;
begin
  p_name    := left(btrim(coalesce(p_name,'')), 120);
  p_phone   := left(btrim(coalesce(p_phone,'')), 30);
  p_address := left(btrim(coalesce(p_address,'')), 400);
  p_zone    := left(btrim(coalesce(p_zone,'')), 80);
  p_promo_code := upper(left(btrim(coalesce(p_promo_code,'')), 40));
  p_delivery_type := lower(btrim(coalesce(p_delivery_type,'home')));
  if p_delivery_type not in ('home','desk') then p_delivery_type := 'home'; end if;

  -- stopdesk collects at the agency: the wilaya suffices, no street address
  if p_name = '' or p_phone = '' or (p_delivery_type = 'home' and p_address = '') then
    raise exception 'MISSING_FIELDS';
  end if;

  p_phone := dz_phone(p_phone);
  if p_phone is null then raise exception 'INVALID_PHONE'; end if;

  -- light anti-spam on the open form
  if (select count(*) from orders
      where dz_phone(phone) = p_phone and created_at > now() - interval '1 hour') >= 5 then
    raise exception 'TOO_MANY_ORDERS';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'INVALID_CART';
  end if;

  select coalesce((value->>'percent')::numeric, 0) into v_promo_pct
  from settings where key = 'promo' and coalesce((value->>'active')::boolean, false);
  if v_promo_pct is null then v_promo_pct := 0; end if;
  v_promo_pct := least(greatest(v_promo_pct, 0), 90);

  select coalesce(nullif(value,'null'::jsonb)::numeric, 0) into v_free_from
  from settings where key = 'free_delivery_from';

  -- fee comes from settings, never from the browser
  select coalesce((z->>(case when p_delivery_type='desk' then 'desk' else 'home' end))::numeric,
                  (z->>'home')::numeric, (z->>'fee')::numeric)
    into v_fee
  from settings s, jsonb_array_elements(s.value) z
  where s.key = 'zones' and z->>'name' = p_zone limit 1;
  if v_fee is null then raise exception 'UNKNOWN_ZONE'; end if;

  for line in select * from jsonb_array_elements(p_items) loop
    begin
      v_pid := (line->>'product_id')::bigint;
      v_qty := floor((line->>'qty')::numeric)::int;
    exception when others then raise exception 'INVALID_CART';
    end;
    if v_qty is null or v_qty < 1 or v_qty > 20 then raise exception 'INVALID_CART'; end if;

    select * into prod from products where id = v_pid and active = true for update;
    if not found then raise exception 'PRODUCT_UNAVAILABLE'; end if;
    if prod.stock < v_qty then raise exception 'OUT_OF_STOCK:%', prod.name_fr; end if;

    v_size := coalesce(line->>'size','');
    if array_length(prod.sizes,1) > 0 and not (v_size = any(prod.sizes)) then
      raise exception 'INVALID_SIZE';
    end if;

    -- same discipline for colour variants
    v_color := coalesce(line->>'color','');
    if array_length(prod.colors,1) > 0 and not (v_color = any(prod.colors)) then
      raise exception 'INVALID_COLOR';
    end if;

    update products set stock = stock - v_qty where id = prod.id;

    v_unit := round(prod.price * (100 - v_promo_pct) / 100, 2);
    v_sub := v_sub + v_unit * v_qty;
    clean := clean || jsonb_build_object(
      'product_id', prod.id,
      'name_fr', prod.name_fr, 'name_ar', prod.name_ar,
      'size', v_size, 'color', v_color, 'qty', v_qty, 'price', v_unit,
      'base_price', prod.price,
      'photo', coalesce(prod.photos[1], ''));
  end loop;

  -- promo code validated against the table, never against browser claims
  if p_promo_code <> '' then
    select * into v_code from promo_codes where upper(code) = p_promo_code and active;
    if not found then raise exception 'INVALID_PROMO'; end if;
    if v_sub < v_code.min_order then raise exception 'PROMO_MIN_ORDER'; end if;
    v_discount := round(v_sub * v_code.percent / 100, 2);
    v_applied_code := v_code.code;
  end if;

  -- free delivery measured AFTER the promo discount, like the checkout preview
  if v_free_from > 0 and (v_sub - v_discount) >= v_free_from then v_fee := 0; end if;

  insert into orders (customer_name, phone, address, zone, delivery_fee, items,
                      subtotal, discount, promo_code, total, status, delivery_type)
  values (p_name, p_phone, p_address, p_zone, v_fee, clean, v_sub,
          v_discount, v_applied_code, v_sub - v_discount + v_fee, 'new', p_delivery_type)
  returning id into v_id;

  return jsonb_build_object('id', v_id, 'subtotal', v_sub, 'discount', v_discount,
    'promo_code', v_applied_code, 'delivery_fee', v_fee, 'delivery_type', p_delivery_type,
    'phone', p_phone, 'total', v_sub - v_discount + v_fee);
end $$;

revoke all on function public.place_order(text,text,text,text,jsonb,text,text) from public;
grant execute on function public.place_order(text,text,text,text,jsonb,text,text) to anon, authenticated;

-- checkout preview of a promo code (only the percentage leaks)
create or replace function public.check_promo(p_code text, p_sub numeric)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare c promo_codes%rowtype;
begin
  select * into c from promo_codes
  where upper(code) = upper(left(btrim(coalesce(p_code,'')), 40)) and active;
  if not found then raise exception 'INVALID_PROMO'; end if;
  if coalesce(p_sub,0) < c.min_order then raise exception 'PROMO_MIN_ORDER'; end if;
  return jsonb_build_object('code', c.code, 'percent', c.percent, 'min_order', c.min_order);
end $$;

revoke all on function public.check_promo(text,numeric) from public;
grant execute on function public.check_promo(text,numeric) to anon, authenticated;

-- ============================================================
-- TRACKING — one order back, only when number AND phone match.
-- Name/address deliberately not returned; phone compared on last 8 digits
-- so 0555123456 matches +213555123456.
-- ============================================================
create or replace function public.track_order(p_id bigint, p_phone text)
returns jsonb language plpgsql security definer set search_path = public, pg_temp
as $$
declare o orders%rowtype; digits text;
begin
  digits := regexp_replace(coalesce(p_phone,''), '\D', '', 'g');
  if p_id is null or length(digits) < 8 then raise exception 'NOT_FOUND'; end if;
  select * into o from orders
  where id = p_id and right(regexp_replace(phone,'\D','','g'), 8) = right(digits, 8);
  if not found then raise exception 'NOT_FOUND'; end if;
  return jsonb_build_object('id', o.id, 'status', o.status, 'created_at', o.created_at,
    'zone', o.zone, 'subtotal', o.subtotal, 'discount', o.discount,
    'promo_code', o.promo_code, 'delivery_fee', o.delivery_fee, 'total', o.total,
    'items', o.items, 'delivery_type', o.delivery_type,
    'carrier', o.carrier, 'tracking_number', o.tracking_number);
end $$;

revoke all on function public.track_order(bigint,text) from public;
grant execute on function public.track_order(bigint,text) to anon, authenticated;

-- cancelling an order puts the items back on the shelf
create or replace function public.restock_cancelled_order()
returns trigger language plpgsql security definer set search_path = public, pg_temp
as $$
declare line jsonb;
begin
  if new.status = 'cancelled' and old.status <> 'cancelled' then
    for line in select * from jsonb_array_elements(new.items) loop
      update products set stock = stock + (line->>'qty')::int
      where id = (line->>'product_id')::bigint;
    end loop;
  end if;
  return new;
end $$;

drop trigger if exists orders_restock on orders;
create trigger orders_restock after update of status on orders
  for each row execute function public.restock_cancelled_order();

-- ============================================================
-- ROW LEVEL SECURITY
-- visitors: read catalogue + storefront settings, nothing else.
-- orders: no direct access at all — place_order()/track_order() are the doors.
-- ============================================================
alter table categories  enable row level security;
alter table products    enable row level security;
alter table orders      enable row level security;
alter table settings    enable row level security;
alter table promo_codes enable row level security;

drop policy if exists "read categories" on categories;
drop policy if exists "read active products" on products;
drop policy if exists "read public settings" on settings;
drop policy if exists "owner all categories" on categories;
drop policy if exists "owner all products" on products;
drop policy if exists "owner all orders" on orders;
drop policy if exists "owner all settings" on settings;
drop policy if exists "owner all promos" on promo_codes;

create policy "read categories" on categories for select using (true);
create policy "read active products" on products for select using (active = true);
create policy "read public settings" on settings
  for select using (key in ('store','zones','promo','free_delivery_from','hero',
                            'whatsapp','announce','socials','exchange_days','ads'));

create policy "owner all categories" on categories
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner all products" on products
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner all orders" on orders
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner all settings" on settings
  for all using (public.is_owner()) with check (public.is_owner());
create policy "owner all promos" on promo_codes
  for all using (public.is_owner()) with check (public.is_owner());

-- ---------- Storage: product photos ----------
insert into storage.buckets (id, name, public) values ('products','products',true)
on conflict (id) do nothing;

drop policy if exists "public read product photos" on storage.objects;
drop policy if exists "owner uploads photos" on storage.objects;
drop policy if exists "owner updates photos" on storage.objects;
drop policy if exists "owner deletes photos" on storage.objects;

create policy "public read product photos" on storage.objects
  for select using (bucket_id = 'products');
create policy "owner uploads photos" on storage.objects
  for insert with check (bucket_id = 'products' and public.is_owner());
create policy "owner updates photos" on storage.objects
  for update using (bucket_id = 'products' and public.is_owner());
create policy "owner deletes photos" on storage.objects
  for delete using (bucket_id = 'products' and public.is_owner());

-- ============================================================
-- LAST STEP — create the owner account:
-- Authentication > Users > Add user (your email + strong password,
-- tick Auto Confirm). Then Sign In / Providers > Email > turn OFF signup.
-- ============================================================
